# config.yaml

# Model paths
keypoint_model:
  config: "COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml"
  weights: "COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml"

densepose_model:
  config: "model_configs/densepose_rcnn_R_50_FPN_s1x.yml"
  weights: "models/model_final_162be9.pkl"

position_model:
  filename: "trained_model.joblib"

# Model parameters
keypoint_score_threshold: 0.7
densepose_score_threshold: 0.5

# Data processing
max_keypoints: 18
mean: 0.5
std: 0.2

# Paths
inputs_dir: "inputs"
outputs_dir: "outputs"