name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      #run: |
        #python -m pip install --upgrade pip
        #pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest tests/ -v --capture=no

  notify-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Notify for deployment
      run: |
        echo "Tests passed successfully. Ready for deployment to EC2."
        echo "Please run 'git pull' on your EC2 instance to deploy the latest changes."